--- #环境分割线
server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles: prod
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  application:
    name: provider-user
  redis:
    host: 192.168.140.128
    port: 6379

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.cloud.pojo

#注册中心配置信息
eureka:
  client: #客户端
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: provider-user                #定义微服务的名称
    prefer-ip-address: true
--- #环境分割线
server:
  port: 8000
  servlet:
    context-path: /

spring:
  profiles: test
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  application:
    name: provider-user
  redis:
    host: 192.168.140.128
    port: 6379

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.cloud.pojo

#注册中心配置信息
eureka:
  client: #客户端
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: provider-user                #定义微服务的名称
    prefer-ip-address: true